config/routes.rb
Chimera::Application.routes.draw do
  devise_for :users

  resources :users do
    resources :friends, :only => [:index, :create, :destroy]
    resources :subscribers, :only => [:index, :create, :destroy]
  end

  match "/profiles/edit" => "profiles#edit"
  resources :profiles, :only => [:create, :index, :show, :update]

  resources :friendrequests, :only =>[:index, :create, :destroy]

  

  match '/about', :to => 'pages#about'
  match '/copyright', :to => 'pages#copyright'

  root :to => 'pages#home'

end

app/models/profile.rb
class Profile < ActiveRecord::Base

  attr_accessible :occupation, :gender, :dob, :mobile, :name, 
  	:zip_code, :state, :country, :city
  belongs_to :user, :foreign_key => "user_id"

  VALID_GENDERS = ["Male", "Female"]
  START_YEAR = 1900
  VALID_DATES = DateTime.new(START_YEAR)..DateTime.now()


  validates(:mobile, :length => {:maximum => 12, :minimum => 10})
  validates(:user_id, :presence => true)
  validates_inclusion_of(:gender, :in => VALID_GENDERS, :presence => true, :message => "Must be male or female")
  #validates_inclusion_of(:dob, :in => VALID_DATES)
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	
	before_filter :authenticate_user!, :except => :show

#	def new
#		if exists
#			render 'edit'
#		else
#			@profile = Profile.new
#			@title = "User profile"
#		end
#	end
#
	def create
		@profile = current_user.build_profile(params[:profile])
		if @profile.save
			flash[:success] = "Profile info updated"
			render 'show'
		else
			@title = "User profile"
			flash[:error] = "Something went wrong. Try again"
			render 'edit'
		end
	end

	def show
		@profile = Profile.find_by_id(params[:id])
		if @profile
			@title = "Profile"
		else
			flash[:notice] = "No such user exists"
			redirect_to root_path
		end
	end

	def edit
		@profile = Profile.find_by_user_id(current_user.id)
		@profile ||= Profile.new
    	@title = "Edit profile"
	end

	def update
		@profile = Profile.find_by_user_id(current_user.id)
		if current_user.profile.update_attributes(params[:profile])
			flash[:success] = "Profile updated"
			render 'show'
		else
			#flash[:notice] = "Something went wrong"
			@title = "Edit user"
			render 'edit'
		end
	end

	def destroy
	end	

	def index
		@profile = Profile.find_by_user_id(current_user.id)
		if @profile
			@title = "Profile"
		else
			@profile = Profile.new
			flash[:notice] = "Profile not created. Create it now."
			render 'edit'
		end
	end
end

app/views/profiles/edit.html.erb
<h1>Edit your profile</h1>

<%= form_for(@profile) do |p| %>
<%= render 'shared/error_messages',
:object => p.object %>

<div class="field">
<%= p.label :name %><br />
<%= p.text_field :name %>
</div>

<h4> Gender: </h4>
<div class="radio">
<%= p.radio_button :gender, "Male" %> MALE <br/>
<%= p.radio_button :gender, "Female" %> FEMALE
</div>

<div class="field">
<%= p.label :mobile %><br />
<%= p.text_field :mobile %>
</div>

<h4> Address- </h4>
<div class="field">
<%= p.label :country %><br />
<%= p.text_field :country %>
</div>

<div class="field">
<%= p.label :state %><br />
<%= p.text_field :state %>
</div>

<div class="field">
<%= p.label :city %><br />
<%= p.text_field :city %>
</div>

<div class="field">
<%= p.label :zip_code %><br />
<%= p.text_field :zip_code %>
</div>

<div class="actions">
<%= p.submit "Update" , :class => "btn btn-success" %>
</div>
<% end %>
<hr/>
    <li>
    <%= link_to('Edit account', edit_user_registration_path) %>
    </li>
    <hr/>

app/views/profiles/index.html.erb
<table class="profile" summary="Profile information">
	<tr>
		<td>
			<h1> Your Profile </h1>
			<h3> Name:  <%= @profile.name %></h3>
			<p> Gender: <%= @profile.gender %> </p>
			<h4> Mobile: <%= @profile.mobile %> </h4>
			<h3> Address: </h3>
			<h4> City: <%= @profile.city %> </h4>
			<h4> State: <%= @profile.state %> </h4>
			<h4> Country: <%= @profile.country %> </h4>
			<p> Pin: <%= @profile.zip_code %> </p>
			<p> <%= link_to "Edit Profile", profiles_edit_path %> </p>
			<p> <%= link_to "MyUrl", @profile %> </p>
		</td>
	</tr>
	<tr>
		<td>
			<span class="badge badge-success"><%= render 'shared/statsFriend' %> </span> <%= link_to "See friends", user_friends_path(@user) %>  <br/>
			<span class="badge badge-info"><%= render 'shared/statsSubscribers' %> </span> <%= link_to "See subscriptions", user_subscribers_path(@user) %> 
		</td>
	</tr>
</table>

app/views/profiles/new.html.erb
<h2> Fill in your profile information </h2>

<%= form_for(@profile) do |p| %>
	<%= render 'shared/error_messages',:object => p.object %>

	<div class="field">
		<%= p.label :name, 'Name' %> <br/>
		<%= p.text_field :name %>
	</div>

	<div class="field">
		<%= p.label :mobile, 'Mobile Num' %> <br/>
		<%= p.text_field :mobile %>
	</div>

	<div class="field">
		<%= p.label :city, 'City' %> <br/>
		<%= p.text_field :city %>
	</div>

	<div class="actions">
		<%= p.submit "Update" %>
	</div>
<% end %>
	

app/views/profiles/show.html.erb
<table class="profile" summary="Profile information">
	<% @user = @profile.user %>
	<tr>
		<td>
			<h3> Name:  <%= @profile.name %></h3>
			<p> Gender: <%= @profile.gender %> </p>
			<h4> Mobile: <%= @profile.mobile %> </h4>
			<h3> Address: </h3>
			<h4> City: <%= @profile.city %> </h4>
			<h4> State: <%= @profile.state %> </h4>
			<h4> Country: <%= @profile.country %> </h4>
			<p> Pin: <%= @profile.zip_code %> </p>
		</td>
	</tr>
	<tr>
		<td>
			<span class="badge badge-success"><%= render 'shared/statsFriend' %> </span> <%= link_to "See friends", user_friends_path(@user) %>  <br/>
			<span class="badge badge-info"><%= render 'shared/statsSubscribers' %> </span> <%= link_to "See subscriptions", user_subscribers_path(@user) %> 
		</td>
		<td>
			
			<% unless current_user == @user %>
				<%= render 'relationships/relation_form' %>
				<%= render 'relationships/subscriber_form' %>
			<% end %>
		</td>
	</tr>
</table>