config/routes.rb
Chimera::Application.routes.draw do
  devise_for :users

  resources :users do
    resources :friends, :only => [:index, :create, :destroy]
    resources :subscribers, :only => [:index, :create, :destroy]
  end

  match "/profiles/edit" => "profiles#edit"
  resources :profiles, :only => [:create, :index, :show, :update]

  resources :friendrequests, :only =>[:index, :create, :destroy]

  

  match '/about', :to => 'pages#about'
  match '/copyright', :to => 'pages#copyright'

  root :to => 'pages#home'

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  self.inheritance_column = nil
  attr_accessible :friend_id, :status, :type
  
  belongs_to :user
  belongs_to :friend, :class_name => "User", :foreign_key => "friend_id"
 
  validates_presence_of :user_id, :friend_id
end

app/views/relationships/_accept_friend_request.html.erb
<%= form_tag user_friends_path(current_user), :method => :post do %>
	<div><%= hidden_field_tag(:userid, user.id) %></div>
	<%= submit_tag "Accept Friend request" %>
<% end %>

app/views/relationships/_cancel_friend_request.html.erb
<%= form_tag friendrequest_path(user), :method => :delete do %>
	<div> <%= hidden_field_tag(:userid, user.id) %> </div>
	<%= submit_tag "Cancel Friend request" %>
<% end %>

app/views/relationships/_follow.html.erb
<%= form_tag user_subscribers_path(current_user), :method => :post do %>
	<div><%= hidden_field_tag(:userid, user.id) %></div>
	<%= submit_tag "Follow" %>
<% end %>

app/views/relationships/_reject_friend_request.html.erb
<%= form_tag friendrequest_path(user), :method => :delete do %>
	<div> <%= hidden_field_tag(:userid, user.id) %> </div>
	<%= submit_tag "Reject Friend request" %>
<% end %>

app/views/relationships/_relation_form.html.erb
<% if current_user.isrequestedfriends?(@user) %>
	
	<%= render :partial => "relationships/accept_friend_request", :locals => {:user => @user } %>
	<%= render :partial => "relationships/reject_friend_request", :locals => {:user => @user } %>
<% elsif current_user.ispendingfriends?(@user) %>
	
	<%= render :partial => "relationships/cancel_friend_request", :locals => {:user => @user } %>
<% elsif current_user.isfriends?(@user) %>
	
	<%= render :partial => "relationships/unfriend", :locals => {:user => @user } %> 
<% else %>
	
	<%= render :partial => "relationships/send_friend_request", :locals => {:user => @user } %>
<% end %>

app/views/relationships/_send_friend_request.html.erb
<%= form_tag friendrequests_path, :method => :post do %>
	<div><%= hidden_field_tag(:userid, user.id) %></div>
	<%= submit_tag "Add Friend" %>
<% end %>

app/views/relationships/_subscriber_form.html.erb
<% if current_user.isfollowing?(@user) %>
	<%= render :partial => "relationships/unfollow", :locals => {:user => @user } %>
<% else %>
	<%= render :partial => "relationships/follow", :locals => {:user => @user } %>
<% end %>

app/views/relationships/_unfollow.html.erb
<%= form_tag user_subscriber_path(user), :method => :delete do %>
	<div> <%= hidden_field_tag(:userid, user.id) %> </div>
	<%= submit_tag "Unfollow" %>
<% end %>

app/views/relationships/_unfriend.html.erb
<%= form_tag user_friend_path(current_user), :method => :delete do %>
	<div> <%= hidden_field_tag(:userid, user.id) %> </div>
	<%= submit_tag "Unfriend" %>
<% end %>