config/routes.rb
Chimera::Application.routes.draw do
  devise_for :users

  resources :users do
    resources :friends, :only => [:index, :create, :destroy]
    resources :subscribers, :only => [:index, :create, :destroy]
  end

  match "/profiles/edit" => "profiles#edit"
  resources :profiles, :only => [:create, :index, :show, :update]

  resources :friendrequests, :only =>[:index, :create, :destroy]

  

  match '/about', :to => 'pages#about'
  match '/copyright', :to => 'pages#copyright'

  root :to => 'pages#home'

end

app/views/layouts/_footer.html.erb
<footer id="page_footer">
<hr/>
<ul>
<li><%= link_to "Contact", "" %></li>
<li><%= link_to "Help", "" %></li>
<li><%= link_to "File a Bug", "" %></li>
</ul>
<p>&copy; 2011 AwesomeCo. All Rights Reserved. All Wrongs Reversed.</p>
</footer>

app/views/layouts/_header.html.erb
<header id="page_header" role="banner">

<h1> [ DWINGG ]</h1>

</header>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</a>
<%= link_to "Dwingg", root_path, :class => 'brand' %>
  <div class="nav-collapse collapse">
    <% if user_signed_in? %>
      <ul class="nav">
        <li class="divider-vertical"></li>
        <li><%= link_to "Profile ", profiles_path %></li>
        <li class="divider-vertical"></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class="icon-shopping-cart"></i> Cart<i class="icon-chevron-right"></i></a>
          <ul class="dropdown-menu">
            <li><a href="#"><i class="icon-shopping-cart"></i> View Cart </a></li>
            <li><a href="#"><i class="icon-star"></i> Wishlist</a></li>
            <li><a href="#"><i class="icon-briefcase"></i> My Wallet</a></li>
            <li><a href="#"><i class="icon-th-list"></i> Purchase History</a></li>
          </ul>
        </li>
        <li class="divider-vertical"></li>
        <li><a href="#contact"><i class="icon-heart"></i> Instinct</a></li>
        <li class="divider-vertical"></li>
        <li>
          <form class="form-search navbar-search">
            <div class="input-append">
            <input type="text" class="span2 search-query" placeholder="What are you Dwingg ?">
            <button type="submit" class="btn"><i class="icon-search"></i> </button>
            </div>
          </form>
        </li>
      </ul>
      <div class="pull-right">
        <ul class="nav">
          <li class="divider-vertical"></li> 
          <li><a href="#"><i class="icon-gift"></i>Gift Central</a></li>
          <li class="divider-vertical"></li> 
          <li><a href="#"> <%= current_user.profile.name %></a></li>
          <li class="divider-vertical navbar-text"></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class="icon-asterisk"></i> </a>
            <ul class="dropdown-menu pull-right">
              <li><a href="#"><i class="icon-wrench"></i> Account Settings </a></li>
              <li><a href="#"><i class="icon-eye-close"></i> Privacy Settings</a></li>
              <li><a href="#"><i class="icon-briefcase"></i> My Wallet</a></li> <hr/>
              <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
        </ul>
      </div>
    <% else %>
       <ul class="nav">
        <li class="divider-vertical"></li>
        <li> <%= link_to('Sign up', new_user_registration_path)  %> </li>
        <li class="divider-vertical"></li>
        <li><a href="#"><i class="icon-shopping-cart"></i>Cart </a></li>
        <li class="divider-vertical"></li>
        <li>
          <form class="form-search navbar-search">
            <div class="input-append">
            <input type="text" class="span2 search-query" placeholder="What are you Dwingg ?">
            <button type="submit" class="btn"><i class="icon-search"></i> </button>
            </div>
          </form>
        </li>
       </ul>
      <div class="pull-right">
        <ul class="nav">
          <li class="divider-vertical"></li> 
          <li><a href="#"><i class="icon-gift"></i>Gift Central</a></li>
          <li class="divider-vertical"></li> 
          <li><%= link_to('Login', new_user_session_path)  %></li>
          <li class="divider-vertical navbar-text"></li>
        </ul>
      </div>
    <% end %>
  </div>
    
       
         <!--/.nav-collapse -->

app/views/layouts/_sidebar.html.erb
       
        <section id="sidebar" class="span2">

          <div class="well sidebar-nav">

            <ul class="nav nav-list" >
              <li> <a href="#"> <img class="img-polaroid" style="width: 140px; height: 140px;" data-src="holder.js/140x140" src="assets/pic.png"> </img> </a></li>
              <li><a href="#"> <h4> <%= link_to current_user.profile.name,  profile_path(4) %></h4></li>
               <li class="divider"> </li>
              <li class="nav-header">Social</li>
              <li><a href="#"><i class="icon-inbox"></i> Inbox</a></li>
              <li class="divider"> </li>
              <li><a href="#"><i class="icon-group"></i> Friends </a> </li>
              <li class="divider"> </li>
              <li><a href="#"><i class="icon-tags"></i> Brands</a></li>
              <li class="divider"> </li>
              <li><a href="#"><i class="icon-star"></i> Wishlist</a></li>
              <li class="divider"> </li>
              <li><a href="#"><i class="icon-credit-card"></i> My Purchases</a></li>
              <li class="divider"> </li>
              <li><a href="#"><i class="icon-eye-open"></i> Watching</i></a></li>
              <li class="divider"> </li>
              <li><a href="#"><i class="icon-heart"></i> Instinct</a></li>
              <li class="divider"> </li>
              <li><a href="#"><i class="icon-magnet"> </i> Pools</a></li>
              <li class="divider"> </li>
              <li><a href="#"><i class="icon-trophy"></i> Achievements</a></li>
              </ul>
          </div><!--/.well -->
        </section>

        <!--/span-->

app/views/layouts/_sidebar_right.html.erb
<section class="span3" id="sidebar">
          <section class="well sidebar-nav" role="activity stream" id="recent_activity">
            <%= render partial: 'activity_items/recent' %>

          </section><!--/.well -->
        </section>

app/views/layouts/_topbar.html.erb
    <div class="navbar navbar-fixed-top" role="navigation" id="utility">
      <div class="navbar-inner">
        <div class="container" >

<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</a>
<%= link_to "Dwingg", root_path, :class => 'brand' %>
  <div class="nav-collapse collapse">
    <% if user_signed_in? %>
      <ul class="nav">
        <li class="divider-vertical"></li>
        <li><%= link_to "Profile ", profiles_path %></li>
        <li class="divider-vertical"></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class="icon-shopping-cart"></i> Cart<i class="icon-chevron-right"></i></a>
          <ul class="dropdown-menu">
            <li><a href="#"><i class="icon-shopping-cart"></i> View Cart </a></li>
            <li><a href="#"><i class="icon-star"></i> Wishlist</a></li>
            <li><a href="#"><i class="icon-briefcase"></i> My Wallet</a></li>
            <li><a href="#"><i class="icon-credit-card"></i> Purchase History</a></li>
          </ul>
        </li>
        <li class="divider-vertical"></li>
        <li><a href="#contact"><i class="icon-heart"></i> Instinct</a></li>
        <li class="divider-vertical"></li>
        <li>
          <form class="form-search navbar-search">
            <div class="input-append">
            <input type="text" class="span3 search-query" placeholder="Search a Person, Brand, Product, Category">
            <button type="submit" class="btn"><i class="icon-search"></i> </button>
            </div>
          </form>
        </li>
      </ul>
      <div class="pull-right">
        <ul class="nav">
          <li class="divider-vertical"></li>
          <li><a href="#"><i class="icon-gift"></i>Gift Central</a></li>
          <li class="divider-vertical"></li>
          <li><a href="#"> <%= current_user.profile.name %></a></li>
          <li class="divider-vertical navbar-text"></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class="icon-cogs"></i> </a>
            <ul class="dropdown-menu pull-right">
              <li><a href="#"><i class="icon-wrench"></i> Account Settings </a></li>
              <li><a href="#"><i class="icon-eye-close"></i> Privacy Settings</a></li>
              <li><a href="#"><i class="icon-briefcase"></i> My Wallet</a></li> <hr/>
              <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
        </ul>
      </div>
    <% else %>
       <ul class="nav">
        <li class="divider-vertical"></li>
        <li> <%= link_to('Sign up', new_user_registration_path) %> </li>
        <li class="divider-vertical"></li>
        <li><a href="#"><i class="icon-shopping-cart"></i>Cart </a></li>
        <li class="divider-vertical"></li>
        <li>
          <form class="form-search navbar-search">
            <div class="input-append">
            <input type="text" class="span2 search-query" placeholder="What are you Dwingg ?">
            <button type="submit" class="btn"><i class="icon-search"></i> </button>
            </div>
          </form>
        </li>
       </ul>
      <div class="pull-right">
        <ul class="nav">
          <li class="divider-vertical"></li>
          <li><a href="#"><i class="icon-gift"></i>Gift Central</a></li>
          <li class="divider-vertical"></li>
          <li><%= link_to('Login', new_user_session_path) %></li>
          <li class="divider-vertical navbar-text"></li>
        </ul>
      </div>
    <% end %>
  </div>
          </div>
      </div>
    </div>
    
       
         <!--/.nav-collapse -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> <%= @title %> | Chimera </title>
    <meta name="description" content="">
    <%= stylesheet_link_tag "application", :media => "all" %> 
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <%= render 'layouts/topbar' %>
    <div id="main" role="main">
      <%= render 'layouts/header' %>

      <div class="container-fluid" >

              <div class="row-fluid">
            <%= render 'layouts/sidebar' %>
            <section id="content" class="span7"> 
              <%= yield %>
            </section>
            <%= render 'layouts/sidebar_right' %>          
          </div>

      </div>  <!--! end of .container -->
      <%= render 'layouts/footer' %>
    </div> <!--! end of #main -->
  </body>

</html>